### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vovayatsyuk** [vovayatsyuk/magento2-alsoviewed#1]
- [x] Module skeleton
- [x] Add backend menu
- [x] Create log table, models and observer that will fill the table
- [x] Grid for log table
- [x] Create relations table and models
- [x] Grid for relations table
- [x] Add mass status and mass delete actions to relations grid
- [x] Manual log processing
- [x] Cronjob log processing
- [x] ~~Inline edit at relations grid~~ (how to implement bidirectional edit with inline mode?)
- [x] Relations form to ~~create new and~~ edit existing relations
- [x] Widget
- [x] ~~Integrate into product edit page at backend~~ (postpone)
- [x] ~~Widget Image for wysisyg editor~~ (postpone)
- [x] Configuration for tab item
- [x] Test styles under Argento theme
- [x] Check duplicate labels in Argento theme
- [x] Add translations
- [x] Add crawlers/ip-address ignore rules
- [x] Write docs
- [x] Publish module at marketplace
